### ISSUE TITLE
Instalación 

### ISSUE THREAD

**Issue by Binblogger** [arian-ota/ota#3]
Cual es el proceso de instalación en el xiaomi 12?

**Comment by nillebor** [comment]
same procedure as LOS17.1
LOS 18.1/19.1 from Arian works very fine and stable

**Comment by Binblogger** [comment]
Pero cual es el método? Por fastboot?

**Comment by nillebor** [comment]
i have the image quite normally installed with the recovery. of course, the recovery for A12/LOS19 should support

i first installed the recovery with fastboot and then started with the recovery. if you like you can still install gapps, magisk or something else.for me, the recovery is updated with every ota the same. this works very well and you try not to worry about anything anymore

please write in english

**Comment by Binblogger** [comment]
thank you very much i was able to install it what should gapps install? I have tried several but they give me an installation error "space error" I have tried nano and gapps specifically for sdk32

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nillebor** [comment]
Are you using current [recovery](https://github.com/arian-ota/ota/releases/download/19.1-davinci_gms-843a9d2f/lineage-19.1-20220713-UNOFFICIAL-GMS-davinci-recovery.img)? you have made a clean installation? With wipe /system and /data?
If you want to have Lineage with google you can use the [GMS version](https://github.com/arian-ota/ota/releases/download/19.1-davinci_gms-843a9d2f/lineage-19.1-20220713-UNOFFICIAL-GMS-davinci.zip), the gapps are already installed there.

Since android12 there are a few problems with the gapps. there is no official at open gapps. but there are also other providers of gapps packages: https://wiki.lineageos.org/gapps or https://nikgapps.com/. 

the nikgapps are available in different packages and sizes. personally, I don't use gapps anymore, I only use [f-droid](https://f-droid.org/) or [aurora-store](https://f-droid.org/de/packages/com.aurora.store/) ([alternative](https://forum.xda-developers.com/t/app-4-4-aurora-store-open-source-play-store-client-april-8-2021.3739733/)) for google apps.

i will be creating a LOS-19 thread at xda for the next few days. Problems can then be posted there. the original thread of pig is no longer maintained.

i hope it helps you

**Comment by Binblogger** [comment]
if i did a clean installation i also tried with the gapps from the official lineage page and it gives me the same problem "installation error due to lack of space" i have cleaned the partitions i have tried

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nillebor** [comment]
do you have wipe all partitions? last firmware?

**Comment by Binblogger** [comment]
if i wiped all partitions the latest firmware is miui 13 chinese rom as my phone is chinese

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nillebor** [comment]
which revovery do you use?
wipe partiotion and factory reset in LOS recovery.

**Comment by Binblogger** [comment]
I'm using the lineage os recovery since I haven't seen a twrp for the xiaomi 12 I've already formatted the partitions and I'm still having problems with the gapps 😔

**Comment by nillebor** [comment]
reboot after install LOS > recovery > flash gapps > reboot
or install [LOS19 gms](https://github.com/arian-ota/ota/releases/download/19.1-davinci_gms-843a9d2f/lineage-19.1-20220713-UNOFFICIAL-GMS-davinci.zip) (with google papps)

**Comment by Binblogger** [comment]
I'm going to try it I'm using the recovery that is in this post

**Comment by drapolas** [comment]
hi, im in xiaomi 12 and impossible to install gapps with twrp and lineageos recovery
the same result enough space
i used differents pico's or nano's gapps 12L and the same
can you help me?
